[project]
name = 'DERFA'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.emergency-relief]
path = 'contracts/emergency-relief.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
